/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useState, useRef } from "react"
import { Html, useGLTF } from "@react-three/drei"
import Hero from "../Hero/Hero"
import {
  WindowUpContainer,
  WindowUpWrapper,
} from "./Pokedex.elements"
import { MeshBasicMaterial } from "three"

export default function Pokedex(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(
    "./models/Pokedex.gltf"
  )
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="pantalla_baja">
          <mesh
            name="Plane002"
            castShadow
            receiveShadow
            geometry={nodes.Plane002.geometry}
            material={nodes.Plane002.material}
          />
          <mesh
            name="Plane002_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane002_1.geometry}
            material={nodes.Plane002_1.material}
          />
        </group>
        <mesh
          name="botones"
          castShadow
          receiveShadow
          geometry={nodes.botones.geometry}
          material={nodes.botones.material}
        />
        <group name="base_baja001">
          <mesh
            name="Plane003"
            castShadow
            receiveShadow
            geometry={nodes.Plane003.geometry}
            material={nodes.Plane003.material}
          />
          <mesh
            name="Plane003_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane003_1.geometry}
            material={nodes.Plane003_1.material}
          />
        </group>
        <mesh
          name="Flechas"
          castShadow
          receiveShadow
          geometry={nodes.Flechas.geometry}
          material={nodes.Flechas.material}
        />
        <group name="Circle001">
          <mesh
            name="Circle002"
            castShadow
            receiveShadow
            geometry={nodes.Circle002.geometry}
            material={nodes.Circle002.material}
          />
          <mesh
            name="Circle002_1"
            castShadow
            receiveShadow
            geometry={nodes.Circle002_1.geometry}
            material={nodes.Circle002_1.material}
          />
        </group>
        <group name="Circle003">
          <mesh
            name="Circle004"
            castShadow
            receiveShadow
            geometry={nodes.Circle004.geometry}
            material={nodes.Circle004.material}
          />
          <mesh
            name="Circle004_1"
            castShadow
            receiveShadow
            geometry={nodes.Circle004_1.geometry}
            material={nodes.Circle004_1.material}
          />
          <mesh
            name="Circle004_2"
            castShadow
            receiveShadow
            geometry={nodes.Circle004_2.geometry}
            material={nodes.Circle004_2.material}
          />
        </group>
        <group name="Plane">
          <mesh
            name="Plane006"
            castShadow
            receiveShadow
            geometry={nodes.Plane006.geometry}
            material={nodes.Plane006.material}
          />
          <mesh
            name="Plane006_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane006_1.geometry}
            material={nodes.Plane006_1.material}
          />
        </group>
        <mesh
          name="Circle006"
          castShadow
          receiveShadow
          geometry={nodes.Circle006.geometry}
          material={nodes.Circle006.material}
        />
        <group name="pantalla_baja001">
          <mesh
            name="Plane007"
            castShadow
            receiveShadow
            geometry={nodes.Plane007.geometry}
            material={nodes.Plane007.material}
          />
          <mesh
            name="Plane007_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane007_1.geometry}
            material={nodes.Plane007_1.material}
          />
        </group>
        <mesh
          name="SECOND"
          castShadow
          receiveShadow
          geometry={nodes.SECOND.geometry}
          material={nodes.SECOND.material}
        />

        <mesh
          name="upWindow"
          castShadow
          receiveShadow
          geometry={nodes.upWindow.geometry}
          // material={nodes.upWindow.material}
        >
          <Html
            position={[0.490698, 3.57098, -1.3]}
            occlude
            transform
            rotation-x={Math.PI * -0.034}
          >
            <WindowUpContainer className="w-c-up">
              <WindowUpWrapper>
                <img
                  src="https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png"
                  alt=""
                />
              </WindowUpWrapper>
            </WindowUpContainer>
          </Html>
        </mesh>
        <mesh
          name="downWindow"
          castShadow
          receiveShadow
          geometry={nodes.downWindow.geometry}
          // material={nodes.downWindow.material}
        >
          <Html
            position={[0.514866, -0.744013, 1.91563]}
            occlude
            transform
            rotation-x={Math.PI * -0.3761897}
          >
            <WindowUpContainer className="w-c-down">
              <WindowUpWrapper>
                <img
                  src="https://pm1.narvii.com/6386/8c71c3ecb24b3c6d628700a610d66b75fa9bcac5_hq.jpg"
                  alt=""
                />
              </WindowUpWrapper>
            </WindowUpContainer>
          </Html>
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload("./models/Pokedex.gltf")

// <mesh
//   name="upWindow"
//   castShadow
//   receiveShadow
//   geometry={nodes.upWindow.geometry}
//   // material={
//   //   new MeshBasicMaterial({ color: "#ff0000" })
//   // }
// >

// </mesh>
